### ISSUE TITLE
Make background automatically cycle, maybe day/night?

### ISSUE THREAD

**Issue by kenerwin88** [Pixel-Map/pixelmap.io#1]

**Comment by CptZiyi** [comment]
![Day vs Night](https://user-images.githubusercontent.com/29252637/131273058-8b56f2f0-6fef-4d5b-a6b3-e249e3c1c52e.jpg)


- First simple fix would be switching between 1 day and 1 night image. First attempt side by side, looks alright imo. 
- I could also try dynamically applying some gradient/filter on the image based on the local time and static day and night times
- 

![Night version](https://user-images.githubusercontent.com/29252637/131273065-84540335-405b-4f1a-a8da-bb8aac58069d.jpg)

**Comment by kenerwin88** [comment]
So cool that @CptZiyi implemented this <3
