### ISSUE TITLE
PixelMap.io is down

### ISSUE THREAD

**Issue by ndbroadbent** [Pixel-Map/pixelmap.io#6]
I'm curious to see what it looked like. Any plans to bring it back online?

**Comment by krazyivan46** [comment]
I will try to fix it even tho I can't fix anything, I think someone has changed the code and the website gets redirected to the spammer.

We need to find someone technically skilled.

I will try to revert the old file.

**Comment by kenerwin88** [comment]
Starting on this :)

**Comment by kenerwin88** [comment]
Back up!
